.TH SORDI 1 "17 Jan 2012"

.SH NAME
.B sordi \- Load and re-serialise RDF data

.SH SYNOPSIS
sordi [OPTION]... INPUT BASE_URI

.SH OPTIONS
.TP
\fB\-h\fR
Print the command line options.

.TP
\fB\-i SYNTAX\fR
Read input in SYNTAX (`turtle' or `ntriples').

.TP
\fB\-o SYNTAX\fR
Write output in SYNTAX (`turtle' or `ntriples').

.TP
\fB\-s INPUT\fR
Parse INPUT as a string (terminates options).

.TP
\fB\-v\fR
Display version information and exit.

.SH AUTHOR
Sordi was written by David Robillard <d@drobilla.net>

.SH COPYRIGHT
Copyright \(co 2011-2016 David Robillard.
.br
License: <http://www.opensource.org/licenses/isc-license>
.br
This is free software; you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.

.SH "SEE ALSO"
<http://drobilla.net/software/sord>
