/* config-taglib.h. Generated by cmake from config-taglib.h.cmake */

/* NOTE: only add something here if it is really needed by all of kdelibs.
   Otherwise please prefer adding to the relevant config-foo.h.cmake file,
   to minimize recompilations and increase modularity. */
/* Define if you have libz */
#cmakedefine   HAVE_ZLIB 1

#cmakedefine   NO_ITUNES_HACKS 1
#cmakedefine   WITH_ASF 1
#cmakedefine   WITH_MP4 1
