# portsmf_test Makefile
# 
# This is intended to be run in the portsmf/portsmf_test directory as:
#   make -f Makefile.osx
# to build portsmf_test.
#
# You can adapt this to build libportsmf.a if you want to use PortSMF
# as a library.

LIBFLAGS = 
CFLAGS = -g -I$(SMFDIR)
CCC = g++ 
CC  = gcc 
SMFDIR = ..

PORTSMFOBJS = 	$(SMFDIR)/allegro.o  \
		$(SMFDIR)/allegrosmfwr.o  \
		$(SMFDIR)/allegrord.o \
		$(SMFDIR)/allegrowr.o \
		$(SMFDIR)/allegrosmfrd.o  \
		$(SMFDIR)/mfmidi.o \
	  	$(SMFDIR)/strparse.o 

PORTSMFHEADERS = $(SMFDIR)/allegro.h  \
		$(SMFDIR)/mfmidi.h \
	  	$(SMFDIR)/strparse.h 

OBJS = $(PORTSMFOBJS)

all: portsmf_test libportsmf.a

libportsmf.a: $(OBJS) Makefile.osx
	ar -crs libportsmf.a $(LIBFLAGS) $(OBJS) 

%.o:%.cpp
	$(CCC) -c $(CFLAGS) $< -o $@

portsmf_test: libportsmf.a portsmf_test.o $(PORTSMFHEADERS)
	$(CCC) $(CFLAGS) -o portsmf_test \
               portsmf_test.o libportsmf.a

clean: 
	rm -f *.o 
