.TH LV2LS 1 "26 Aug 2016"

.SH NAME
.B lv2ls \- list all installed LV2 plugins

.SH SYNOPSIS
.B lv2ls [OPTION]...

.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-names\fR
Show names instead of URIs

.TP
\fB\-\-help\fR
Display help and exit

.TP
\fB\-\-version\fR
Display version information and exit

.SH "SEE ALSO"
.BR lilv(3),
.BR lv2info(1)

.SH AUTHOR
lv2ls was written by David Robillard <d@drobilla.net>
.PP
This manual page was written by Jaromír Mikes <mira.mikes@seznam.cz>
and David Robillard <d@drobilla.net>
