# PrepareDepsSources.cmake - pre-fetch dep sources into the cache.
#
#   cmake [-DEXTDEPS_CACHE=<dir>] -P buildscripts/cmake/PrepareDepsSources.cmake
#
# This lets source/REBUILD and offline/distro builds configure without network.
# SYSTEM deps and deps without a recipe are skipped.

cmake_minimum_required(VERSION 3.24)
set(_self_dir "${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(_root "${_self_dir}/../.." ABSOLUTE)
set(EXTDEPS_DIR "${_root}/muse_deps")

include("${EXTDEPS_DIR}/buildtools/build_dependency.cmake")

if (EXTDEPS_CACHE)
    set(ENV{EXTDEPS_CACHE} "${EXTDEPS_CACHE}")
endif()
_bd_resolve_cache(EXTDEPS_CACHE)

# Fetch + SHA-verify one tarball into <cache>/downloads/<name>/<basename>.
function(_pds_tarball name label url sha256)
    get_filename_component(_basename "${url}" NAME)
    if (_basename MATCHES "^git_revision:")
        set(_basename "${label}.zip")
    endif()
    set(_download_dir "${EXTDEPS_CACHE}/downloads/${name}")
    set(_archive "${_download_dir}/${_basename}")
    if (EXISTS "${_archive}")
        file(SHA256 "${_archive}" _got_sha256)
        if (_got_sha256 STREQUAL "${sha256}")
            message(STATUS "[prepare] cached ${name}/${_basename}")
            return()
        endif()
    endif()
    file(MAKE_DIRECTORY "${_download_dir}")
    message(STATUS "[prepare] fetch ${name}/${_basename}")

    # Try the release mirror first. Fetch from upstream when the pin is new.
    _bd_mirror("${EXTDEPS_DIR}" _mirror)
    set(_urls "")
    if (_mirror)
        _bd_src_ext("${_basename}" _ext)
        list(APPEND _urls "${_mirror}/${label}-src.${_ext}")
    endif()
    list(APPEND _urls "${url}")
    _bd_fetch("${_archive}" "${sha256}" ${_urls})
endfunction()

# Resolve a dep's version (metadata DEP_VERSION) and include its spec. Sets
# <out_spec> to the spec path, "" if there is no recipe.
function(_pds_spec name out_spec out_version)
    set(_spec "${EXTDEPS_DIR}/recipes/${name}/spec.cmake")
    set(_version "")
    if (EXISTS "${_spec}")
        include("${_spec}")            # the recipe defines DEP_VERSION
        set(_version "${DEP_VERSION}")
    else()
        set(_spec "")
    endif()
    set(${out_spec} "${_spec}" PARENT_SCOPE)
    set(${out_version} "${_version}" PARENT_SCOPE)
endfunction()

function(_pds_single name)
    _pds_spec("${name}" spec version)
    if (NOT spec)
        message(STATUS "[prepare] skip ${name} (no recipe)")
        return()
    endif()
    include("${spec}")
    if (NOT DEFINED DEP_SOURCE_URL OR NOT DEFINED DEP_SOURCE_SHA256)
        message(STATUS "[prepare] skip ${name} (no tarball source)")
        return()
    endif()
    _pds_tarball("${name}" "${name}-${version}" "${DEP_SOURCE_URL}" "${DEP_SOURCE_SHA256}")
endfunction()

function(require_dep name)
    if ("${ARGV1}" STREQUAL "SYSTEM")
        message(STATUS "[prepare] skip ${name} (system)")
    elseif ("${ARGV1}" STREQUAL "REBUILD" OR "${ARGV1}" STREQUAL "")
        _pds_single("${name}")
    else()
        message(FATAL_ERROR "[prepare] ${name}: require_dep accepts only REBUILD or SYSTEM (got '${ARGV1}')")
    endif()
endfunction()

function(require_tool name)
    _pds_single("${name}")
    _pds_sources("${name}")
endfunction()

# Source-delivery deps and recipes with extra source pins: each DEP_SOURCES
# entry, "sub|tarball|url|sha256" fetched + verified or "sub|git|repo|commit"
# cloned + checked out, into the same cache layout the engine reads.
function(_pds_sources name)
    _pds_spec("${name}" spec version)
    if (NOT spec)
        return()
    endif()
    include("${spec}")
    set(_download_dir "${EXTDEPS_CACHE}/downloads/${name}")
    file(MAKE_DIRECTORY "${_download_dir}")
    find_program(GIT NAMES git)
    foreach(_source ${DEP_SOURCES})
        _bd_parse_source("${_source}" _source_sub _source_kind _source_location _source_pin)
        if (_source_kind STREQUAL "tarball")
            if (_source_sub STREQUAL name)
                set(label "${name}-${version}")
            else()
                set(label "${name}-${_source_sub}")
            endif()
            _pds_tarball("${name}" "${label}" "${_source_location}" "${_source_pin}")
        else() # git commit
            set(_git_dir "${_download_dir}/${_source_sub}.git")
            if (NOT GIT)
                message(FATAL_ERROR "[prepare] git required to prefetch ${name}/${_source_sub}")
            endif()
            if (NOT EXISTS "${_git_dir}/.git")
                execute_process(COMMAND ${GIT} clone --quiet "${_source_location}" "${_git_dir}" RESULT_VARIABLE _result)
                if (NOT _result EQUAL 0)
                    file(REMOVE_RECURSE "${_git_dir}")
                    message(FATAL_ERROR "[prepare] ${name}/${_source_sub} clone failed (${_source_location})")
                endif()
            endif()
            _bd_run_dir("${_git_dir}" ${GIT} checkout --quiet "${_source_pin}")
            execute_process(COMMAND ${GIT} -C "${_git_dir}" rev-parse HEAD
                            OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE)
            if (NOT _head STREQUAL "${_source_pin}")
                message(FATAL_ERROR "[prepare] ${name}/${_source_sub}: HEAD ${_head} != pinned ${_source_pin}")
            endif()
            message(STATUS "[prepare] git ${name}/${_source_sub} @ ${_source_pin}")
        endif()
    endforeach()
endfunction()

function(require_source_dep name)
    if ("${ARGV1}" STREQUAL "SYSTEM")
        message(STATUS "[prepare] skip ${name} (system)")
        return()
    elseif (NOT "${ARGV1}" STREQUAL "")
        message(FATAL_ERROR "[prepare] ${name}: require_source_dep accepts only SYSTEM (got '${ARGV1}')")
    endif()
    _pds_sources("${name}")
endfunction()

# Run the manifest once per OS_IS_WIN value so the cache is the platform union
# (openssl is non-Windows). Fetching is idempotent (SHA-checked).
macro(_pds_manifest win)
    set(OS_IS_LIN FALSE)
    set(OS_IS_FBSD FALSE)
    set(OS_IS_MAC FALSE)
    set(OS_IS_WIN ${win})
    set(AU_USE_LIBCURL ON)
    set(AU_MODULE_EFFECTS_LV2 ON)
    set(CMAKE_CXX_COMPILER_ARCHITECTURE_ID "x86_64")
    set(MUSE_MODULE_VST ON)
    set(MUSE_MODULE_DRAW ON)
    set(MUSE_MODULE_AUDIO ON)
    set(MUSE_MODULE_AUDIO_EXPORT ON)
    set(MUSE_MODULE_DIAGNOSTICS_CRASHPAD_CLIENT ON)
    include("${_self_dir}/DependencyManifest.cmake")
    include("${_root}/muse/buildscripts/cmake/ExtDepsManifest.cmake")
endmacro()
_pds_manifest(FALSE)
_pds_manifest(TRUE)
message(STATUS "[prepare] sources ready in ${EXTDEPS_CACHE}/downloads")
