#!/usr/bin/env python3
"""Scan share/nyquist-plug-ins/*.ny for (_ ...) / (_C ...) / (NGETTEXT ...) /
(NGETTEXTC ...) and emit a never-compiled C++ stub that lupdate scans.
All strings keyed to context "effects-nyquist" to match NyquistBase.cpp."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
NY_DIR = REPO / "share" / "nyquist-plug-ins"


_STRING_RE = re.compile(r'"((?:\\.|[^"\\])*)"')


def parse_lisp_strings_after(src: str, start: int, count: int) -> list[str] | None:
    """Read `count` consecutive double-quoted strings starting at src[start].
    Skips whitespace and Lisp `;` comments. Returns None on miss."""
    out: list[str] = []
    i = start
    n = len(src)
    while len(out) < count and i < n:
        while i < n and src[i] in " \t\r\n":
            i += 1
        if i < n and src[i] == ";":
            while i < n and src[i] != "\n":
                i += 1
            continue
        if i >= n or src[i] != '"':
            return None
        m = _STRING_RE.match(src, i)
        if m is None:
            return None
        out.append(m.group(1))
        i = m.end()
    return out if len(out) == count else None


def extract_from(text: str) -> list[tuple[str, str, str, str]]:
    """Return (form, singular, plural_or_empty, context_or_empty) tuples."""
    out: list[tuple[str, str, str, str]] = []

    for m in re.finditer(r"\(_\s+", text):
        strs = parse_lisp_strings_after(text, m.end(), 1)
        if strs:
            out.append(("_", strs[0], "", ""))

    for m in re.finditer(r"\(_C\s+", text):
        strs = parse_lisp_strings_after(text, m.end(), 2)
        if strs:
            out.append(("_C", strs[0], "", strs[1]))

    for m in re.finditer(r"\(NGETTEXT\s+", text):
        strs = parse_lisp_strings_after(text, m.end(), 2)
        if strs:
            # Plural form is dropped: muse::trc("ctx", sing, nullptr, 1) has no
            # slot for it; translators get plurals from lupdate's numerus form.
            out.append(("NGETTEXT", strs[0], "", ""))

    for m in re.finditer(r"\(NGETTEXTC\s+", text):
        # (NGETTEXTC singular plural n context). Skip the numeric n to reach context.
        strs = parse_lisp_strings_after(text, m.end(), 2)
        if strs is None:
            continue
        i = m.end()
        for _ in range(2):
            while i < len(text) and text[i] in " \t\r\n":
                i += 1
            sm = _STRING_RE.match(text, i)
            if sm is None:
                break
            i = sm.end()
        while i < len(text) and text[i] in " \t\r\n":
            i += 1
        while i < len(text) and text[i] not in " \t\r\n)":
            i += 1
        ctx_list = parse_lisp_strings_after(text, i, 1)
        if ctx_list:
            out.append(("NGETTEXTC", strs[0], "", ctx_list[0]))

    return out


def _escape_for_cpp(s: str) -> str:
    return (s.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("\n", "\\n")
             .replace("\r", "\\r")
             .replace("\t", "\\t"))


def emit_stub(entries: list[tuple[str, str, str, str]], output: Path) -> None:
    lines: list[str] = [
        "// Auto-generated by tools/translations/extract_nyquist_strings.py.",
        "// Never compiled; only scanned by lupdate.",
        "",
        "#include <muse/framework/global/translation.h>",
        "",
        "static void _nyquist_strings_for_lupdate_only()",
        "{",
    ]
    for form, sing, plur, ctx in entries:
        sing_esc = _escape_for_cpp(sing)
        ctx_esc = _escape_for_cpp(ctx) if ctx else ""
        if form == "_":
            lines.append(f'    (void)muse::trc("effects-nyquist", "{sing_esc}");')
        elif form == "_C":
            lines.append(f'    (void)muse::trc("effects-nyquist", "{sing_esc}", "{ctx_esc}");')
        elif form == "NGETTEXT":
            lines.append(f'    (void)muse::trc("effects-nyquist", "{sing_esc}", nullptr, 1);')
        elif form == "NGETTEXTC":
            lines.append(f'    (void)muse::trc("effects-nyquist", "{sing_esc}", "{ctx_esc}", 1);')
    lines.append("}")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", required=True,
                    type=Path, help="path to emit the generated stub")
    ap.add_argument("--ny-dir", default=NY_DIR, type=Path,
                    help="directory to scan (default: share/nyquist-plug-ins)")
    args = ap.parse_args()

    all_entries: list[tuple[str, str, str, str]] = []
    if args.ny_dir.exists():
        for ny in sorted(args.ny_dir.glob("*.ny")):
            text = ny.read_text(encoding="utf-8", errors="replace")
            all_entries.extend(extract_from(text))

    seen: set[tuple[str, str, str, str]] = set()
    deduped: list[tuple[str, str, str, str]] = []
    for e in all_entries:
        if e in seen:
            continue
        seen.add(e)
        deduped.append(e)

    emit_stub(deduped, args.output)
    print(f"[ny-extract] {len(deduped)} unique entries -> {args.output}",
          file=sys.stderr)


if __name__ == "__main__":
    main()
