#
# GNU makefile
#

topdir = ../../..
libdir = $(topdir)/objs/$(BUILD)/lib

LIB_NAME = libutf8

ifeq ($(OS),Darwin)
    EXPLICIT_LIBS = $(libdir)/libgrabbag.a $(ICONV_LIBS)
else
    LIBS = -lgrabbag $(ICONV_LIBS)
endif

INCLUDES = -I$(topdir)/include

SRCS_C = \
	charset.c \
	iconvert.c \
	utf8.c

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
