#!/bin/bash

function waf
{
   pkg=$1
   pushd >/dev/null ${pkg}
   shift
   $(which python python2 | tail -1) waf --prefix="." --include="." $@ build || exit 1
   popd >/dev/null 

   export PKG_CONFIG_PATH="$(pwd)/${pkg}/build:${PKG_CONFIG_PATH}"
   export CFLAGS="-I$(pwd)/${pkg} ${CFLAGS}"
   export LDFLAGS="-L$(pwd)/${pkg} -l${pkg}-0 ${LDFLAGS}"

   if [ -e ${pkg}/build/*.a ]
   then
      mkdir -p obj
      pushd obj
      ar vx ../${pkg}/build/*.a
      ar vq ../liblv2.a *
      popd
      rm -rf obj
   fi
}

[ -e liblv2.a ] && exit 0

waf lv2 --no-plugins
waf serd --no-utils --static --no-shared
waf sord --no-utils --static --no-shared
waf sratom --static --no-shared
waf lilv --no-utils --static --no-shared

exit 0
