EXTRA_DIST += \
	portaudio-v19/bindings/cpp/aclocal.m4 \
	portaudio-v19/bindings/cpp/AUTHORS \
	portaudio-v19/bindings/cpp/bin/Makefile.am \
	portaudio-v19/bindings/cpp/bin/Makefile.in \
	portaudio-v19/bindings/cpp/build/gnu/aclocal.m4 \
	portaudio-v19/bindings/cpp/build/gnu/config.guess \
	portaudio-v19/bindings/cpp/build/gnu/config.sub \
	portaudio-v19/bindings/cpp/build/gnu/configure \
	portaudio-v19/bindings/cpp/build/gnu/configure.ac \
	portaudio-v19/bindings/cpp/build/gnu/install-sh \
	portaudio-v19/bindings/cpp/build/gnu/Makefile.in \
	portaudio-v19/bindings/cpp/build/gnu/OUT_OF_DATE \
	portaudio-v19/bindings/cpp/build/vc6/devs_example.dsp \
	portaudio-v19/bindings/cpp/build/vc6/devs_example.dsw \
	portaudio-v19/bindings/cpp/build/vc6/sine_example.dsp \
	portaudio-v19/bindings/cpp/build/vc6/sine_example.dsw \
	portaudio-v19/bindings/cpp/build/vc6/static_library.dsp \
	portaudio-v19/bindings/cpp/build/vc6/static_library.dsw \
	portaudio-v19/bindings/cpp/build/vc7_1/devs_example.sln \
	portaudio-v19/bindings/cpp/build/vc7_1/devs_example.vcproj \
	portaudio-v19/bindings/cpp/build/vc7_1/sine_example.sln \
	portaudio-v19/bindings/cpp/build/vc7_1/sine_example.vcproj \
	portaudio-v19/bindings/cpp/build/vc7_1/static_library.sln \
	portaudio-v19/bindings/cpp/build/vc7_1/static_library.vcproj \
	portaudio-v19/bindings/cpp/build/vc7/OUT_OF_DATE \
	portaudio-v19/bindings/cpp/ChangeLog \
	portaudio-v19/bindings/cpp/configure \
	portaudio-v19/bindings/cpp/configure.ac \
	portaudio-v19/bindings/cpp/COPYING \
	portaudio-v19/bindings/cpp/doc/config.doxy \
	portaudio-v19/bindings/cpp/doc/config.doxy.linux \
	portaudio-v19/bindings/cpp/doc/Makefile.am \
	portaudio-v19/bindings/cpp/doc/Makefile.in \
	portaudio-v19/bindings/cpp/doc/README \
	portaudio-v19/bindings/cpp/example/devs.cxx \
	portaudio-v19/bindings/cpp/example/sine.cxx \
	portaudio-v19/bindings/cpp/include/Makefile.am \
	portaudio-v19/bindings/cpp/include/Makefile.in \
	portaudio-v19/bindings/cpp/include/portaudiocpp/AsioDeviceAdapter.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/AutoSystem.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/BlockingStream.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/CallbackInterface.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/CallbackStream.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/CFunCallbackStream.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/CppFunCallbackStream.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/Device.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/DirectionSpecificStreamParameters.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/Exception.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/HostApi.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/InterfaceCallbackStream.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/MemFunCallbackStream.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/PortAudioCpp.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/SampleDataFormat.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/Stream.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/StreamParameters.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/SystemDeviceIterator.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/SystemHostApiIterator.hxx \
	portaudio-v19/bindings/cpp/include/portaudiocpp/System.hxx \
	portaudio-v19/bindings/cpp/INSTALL \
	portaudio-v19/bindings/cpp/lib/Makefile.am \
	portaudio-v19/bindings/cpp/lib/Makefile.in \
	portaudio-v19/bindings/cpp/Makefile.am \
	portaudio-v19/bindings/cpp/Makefile.in \
	portaudio-v19/bindings/cpp/NEWS \
	portaudio-v19/bindings/cpp/portaudiocpp.pc.in \
	portaudio-v19/bindings/cpp/README \
	portaudio-v19/bindings/cpp/SConscript \
	portaudio-v19/bindings/cpp/source/portaudiocpp/AsioDeviceAdapter.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/BlockingStream.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/CallbackInterface.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/CallbackStream.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/CFunCallbackStream.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/CppFunCallbackStream.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/Device.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/DirectionSpecificStreamParameters.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/Exception.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/HostApi.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/InterfaceCallbackStream.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/MemFunCallbackStream.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/Stream.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/StreamParameters.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/System.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/SystemDeviceIterator.cxx \
	portaudio-v19/bindings/cpp/source/portaudiocpp/SystemHostApiIterator.cxx \
	portaudio-v19/bindings/java/c/build/vs2010/PortAudioJNI/PortAudioJNI.sln \
	portaudio-v19/bindings/java/c/build/vs2010/PortAudioJNI/PortAudioJNI.vcproj \
	portaudio-v19/bindings/java/c/build/vs2010/PortAudioJNI/PortAudioJNI.vcxproj \
	portaudio-v19/bindings/java/c/src/com_portaudio_BlockingStream.c \
	portaudio-v19/bindings/java/c/src/com_portaudio_BlockingStream.h \
	portaudio-v19/bindings/java/c/src/com_portaudio_PortAudio.c \
	portaudio-v19/bindings/java/c/src/com_portaudio_PortAudio.h \
	portaudio-v19/bindings/java/c/src/jpa_tools.c \
	portaudio-v19/bindings/java/c/src/jpa_tools.h \
	portaudio-v19/bindings/java/jportaudio/.classpath \
	portaudio-v19/bindings/java/jportaudio.dox \
	portaudio-v19/bindings/java/jportaudio/jtests/com/portaudio/PlaySine.java \
	portaudio-v19/bindings/java/jportaudio/jtests/com/portaudio/TestBasic.java \
	portaudio-v19/bindings/java/jportaudio/.project \
	portaudio-v19/bindings/java/jportaudio/src/com/portaudio/BlockingStream.java \
	portaudio-v19/bindings/java/jportaudio/src/com/portaudio/DeviceInfo.java \
	portaudio-v19/bindings/java/jportaudio/src/com/portaudio/HostApiInfo.java \
	portaudio-v19/bindings/java/jportaudio/src/com/portaudio/PortAudio.java \
	portaudio-v19/bindings/java/jportaudio/src/com/portaudio/StreamInfo.java \
	portaudio-v19/bindings/java/jportaudio/src/com/portaudio/StreamParameters.java \
	portaudio-v19/bindings/java/scripts/make_header.bat \
	portaudio-v19/build/msvc/portaudio.def \
	portaudio-v19/build/msvc/portaudio.dsp \
	portaudio-v19/build/msvc/portaudio.dsw \
	portaudio-v19/build/msvc/portaudio.sln \
	portaudio-v19/build/msvc/portaudio.vcproj \
	portaudio-v19/build/msvc/readme.txt \
	portaudio-v19/build/scons/SConscript_common \
	portaudio-v19/build/scons/SConscript_opts \
	portaudio-v19/CMakeLists.txt \
	portaudio-v19/cmake_support/FindASIOSDK.cmake \
	portaudio-v19/cmake_support/FindDXSDK.cmake \
	portaudio-v19/cmake_support/options_cmake.h.in \
	portaudio-v19/cmake_support/template_portaudio.def \
	portaudio-v19/config.guess \
	portaudio-v19/config.sub \
	portaudio-v19/configure \
	portaudio-v19/configure.in \
	portaudio-v19/depcomp \
	portaudio-v19/doc/src/api_overview.dox \
	portaudio-v19/doc/src/images/portaudio-external-architecture-diagram.png \
	portaudio-v19/doc/src/license.dox \
	portaudio-v19/doc/src/mainpage.dox \
	portaudio-v19/doc/src/srcguide.dox \
	portaudio-v19/doc/src/tutorial/blocking_read_write.dox \
	portaudio-v19/doc/src/tutorial/compile_cmake.dox \
	portaudio-v19/doc/src/tutorial/compile_linux.dox \
	portaudio-v19/doc/src/tutorial/compile_mac_coreaudio.dox \
	portaudio-v19/doc/src/tutorial/compile_windows_asio_msvc.dox \
	portaudio-v19/doc/src/tutorial/compile_windows.dox \
	portaudio-v19/doc/src/tutorial/compile_windows_mingw.dox \
	portaudio-v19/doc/src/tutorial/exploring.dox \
	portaudio-v19/doc/src/tutorial/initializing_portaudio.dox \
	portaudio-v19/doc/src/tutorial/open_default_stream.dox \
	portaudio-v19/doc/src/tutorial/querying_devices.dox \
	portaudio-v19/doc/src/tutorial/start_stop_abort.dox \
	portaudio-v19/doc/src/tutorial/terminating_portaudio.dox \
	portaudio-v19/doc/src/tutorial/tutorial_start.dox \
	portaudio-v19/doc/src/tutorial/utility_functions.dox \
	portaudio-v19/doc/src/tutorial/writing_a_callback.dox \
	portaudio-v19/doc/utils/checkfiledocs.py \
	portaudio-v19/Doxyfile \
	portaudio-v19/Doxyfile.developer \
	portaudio-v19/examples/CMakeLists.txt \
	portaudio-v19/examples/pa_devs.c \
	portaudio-v19/examples/paex_mono_asio_channel_select.c \
	portaudio-v19/examples/paex_ocean_shore.c \
	portaudio-v19/examples/paex_pink.c \
	portaudio-v19/examples/paex_read_write_wire.c \
	portaudio-v19/examples/paex_record.c \
	portaudio-v19/examples/paex_record_file.c \
	portaudio-v19/examples/paex_saw.c \
	portaudio-v19/examples/paex_sine.c \
	portaudio-v19/examples/paex_sine_c++.cpp \
	portaudio-v19/examples/paex_wmme_ac3.c \
	portaudio-v19/examples/paex_wmme_surround.c \
	portaudio-v19/examples/paex_write_sine.c \
	portaudio-v19/examples/paex_write_sine_nonint.c \
	portaudio-v19/examples/pa_fuzz.c \
	portaudio-v19/fixdir.bat \
	portaudio-v19/fixfile.bat \
	portaudio-v19/include/pa_asio.h \
	portaudio-v19/include/pa_jack.h \
	portaudio-v19/include/pa_linux_alsa.h \
	portaudio-v19/include/pa_mac_core.h \
	portaudio-v19/include/pa_unix_oss.h \
	portaudio-v19/include/pa_win_ds.h \
	portaudio-v19/include/pa_win_wasapi.h \
	portaudio-v19/include/pa_win_waveformat.h \
	portaudio-v19/include/pa_win_wdmks.h \
	portaudio-v19/include/pa_win_wmme.h \
	portaudio-v19/include/portaudio.h \
	portaudio-v19/index.html \
	portaudio-v19/install-sh \
	portaudio-v19/jack.patch \
	portaudio-v19/libtool22.patch \
	portaudio-v19/LICENSE.txt \
	portaudio-v19/ltmain.sh \
	portaudio-v19/Makefile.in \
	portaudio-v19/missing \
	portaudio-v19/pablio/pablio.c \
	portaudio-v19/pablio/pablio.def \
	portaudio-v19/pablio/pablio.h \
	portaudio-v19/pablio/README.txt \
	portaudio-v19/pablio/test_rw.c \
	portaudio-v19/pablio/test_rw_echo.c \
	portaudio-v19/pablio/test_w_saw8.c \
	portaudio-v19/pablio/test_w_saw.c \
	portaudio-v19/portaudio-2.0.pc.in \
	portaudio-v19/qa/loopback/README.txt \
	portaudio-v19/qa/loopback/src/audio_analyzer.c \
	portaudio-v19/qa/loopback/src/audio_analyzer.h \
	portaudio-v19/qa/loopback/src/biquad_filter.c \
	portaudio-v19/qa/loopback/src/biquad_filter.h \
	portaudio-v19/qa/loopback/src/paqa.c \
	portaudio-v19/qa/loopback/src/paqa_tools.c \
	portaudio-v19/qa/loopback/src/paqa_tools.h \
	portaudio-v19/qa/loopback/src/qa_tools.h \
	portaudio-v19/qa/loopback/src/test_audio_analyzer.c \
	portaudio-v19/qa/loopback/src/test_audio_analyzer.h \
	portaudio-v19/qa/loopback/src/write_wav.c \
	portaudio-v19/qa/loopback/src/write_wav.h \
	portaudio-v19/qa/paqa_devs.c \
	portaudio-v19/qa/paqa_errs.c \
	portaudio-v19/qa/paqa_latency.c \
	portaudio-v19/README.configure.txt \
	portaudio-v19/README.txt \
	portaudio-v19/SConstruct \
	portaudio-v19/src/common/pa_allocation.c \
	portaudio-v19/src/common/pa_allocation.h \
	portaudio-v19/src/common/pa_converters.c \
	portaudio-v19/src/common/pa_converters.h \
	portaudio-v19/src/common/pa_cpuload.c \
	portaudio-v19/src/common/pa_cpuload.h \
	portaudio-v19/src/common/pa_debugprint.c \
	portaudio-v19/src/common/pa_debugprint.h \
	portaudio-v19/src/common/pa_dither.c \
	portaudio-v19/src/common/pa_dither.h \
	portaudio-v19/src/common/pa_dynload.c \
	portaudio-v19/src/common/pa_dynload.h \
	portaudio-v19/src/common/pa_endianness.h \
	portaudio-v19/src/common/pa_front.c \
	portaudio-v19/src/common/pa_hostapi.h \
	portaudio-v19/src/common/pa_memorybarrier.h \
	portaudio-v19/src/common/pa_process.c \
	portaudio-v19/src/common/pa_process.h \
	portaudio-v19/src/common/pa_ringbuffer.c \
	portaudio-v19/src/common/pa_ringbuffer.h \
	portaudio-v19/src/common/pa_stream.c \
	portaudio-v19/src/common/pa_stream.h \
	portaudio-v19/src/common/pa_trace.c \
	portaudio-v19/src/common/pa_trace.h \
	portaudio-v19/src/common/pa_types.h \
	portaudio-v19/src/common/pa_util.h \
	portaudio-v19/src/hostapi/alsa/pa_linux_alsa.c \
	portaudio-v19/src/hostapi/asihpi/pa_linux_asihpi.c \
	portaudio-v19/src/hostapi/asio/ASIO-README.txt \
	portaudio-v19/src/hostapi/asio/Callback_adaptation_.pdf \
	portaudio-v19/src/hostapi/asio/iasiothiscallresolver.cpp \
	portaudio-v19/src/hostapi/asio/iasiothiscallresolver.h \
	portaudio-v19/src/hostapi/asio/pa_asio.cpp \
	portaudio-v19/src/hostapi/asio/Pa_ASIO.pdf \
	portaudio-v19/src/hostapi/coreaudio/notes.txt \
	portaudio-v19/src/hostapi/coreaudio/pa_mac_core_blocking.c \
	portaudio-v19/src/hostapi/coreaudio/pa_mac_core_blocking.h \
	portaudio-v19/src/hostapi/coreaudio/pa_mac_core.c \
	portaudio-v19/src/hostapi/coreaudio/pa_mac_core_internal.h \
	portaudio-v19/src/hostapi/coreaudio/pa_mac_core_old.c \
	portaudio-v19/src/hostapi/coreaudio/pa_mac_core_utilities.c \
	portaudio-v19/src/hostapi/coreaudio/pa_mac_core_utilities.h \
	portaudio-v19/src/hostapi/dsound/pa_win_ds.c \
	portaudio-v19/src/hostapi/dsound/pa_win_ds_dynlink.c \
	portaudio-v19/src/hostapi/dsound/pa_win_ds_dynlink.h \
	portaudio-v19/src/hostapi/jack/pa_jack.c \
	portaudio-v19/src/hostapi/jack/pa_jack_dynload.c \
	portaudio-v19/src/hostapi/jack/pa_jack_dynload.h \
	portaudio-v19/src/hostapi/oss/low_latency_tip.txt \
	portaudio-v19/src/hostapi/oss/pa_unix_oss.c \
	portaudio-v19/src/hostapi/oss/recplay.c \
	portaudio-v19/src/hostapi/skeleton/pa_hostapi_skeleton.c \
	portaudio-v19/src/hostapi/skeleton/README.txt \
	portaudio-v19/src/hostapi/wasapi/mingw-include/audioclient.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/AudioSessionTypes.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/devicetopology.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/endpointvolume.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/FunctionDiscoveryKeys_devpkey.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/functiondiscoverykeys.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/ksguid.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/ks.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/ksmedia.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/ksproxy.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/ksuuids.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/mmdeviceapi.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/propidl.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/propkeydef.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/propkey.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/propsys.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/rpcsal.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/sal.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/sdkddkver.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/shtypes.h \
	portaudio-v19/src/hostapi/wasapi/mingw-include/structuredquery.h \
	portaudio-v19/src/hostapi/wasapi/pa_win_wasapi.c \
	portaudio-v19/src/hostapi/wasapi/readme.txt \
	portaudio-v19/src/hostapi/wdmks/pa_win_wdmks.c \
	portaudio-v19/src/hostapi/wdmks/readme.txt \
	portaudio-v19/src/hostapi/wmme/pa_win_wmme.c \
	portaudio-v19/src/os/unix/pa_unix_hostapis.c \
	portaudio-v19/src/os/unix/pa_unix_util.c \
	portaudio-v19/src/os/unix/pa_unix_util.h \
	portaudio-v19/src/os/win/pa_win_coinitialize.c \
	portaudio-v19/src/os/win/pa_win_coinitialize.h \
	portaudio-v19/src/os/win/pa_win_hostapis.c \
	portaudio-v19/src/os/win/pa_win_util.c \
	portaudio-v19/src/os/win/pa_win_waveformat.c \
	portaudio-v19/src/os/win/pa_win_wdmks_utils.c \
	portaudio-v19/src/os/win/pa_win_wdmks_utils.h \
	portaudio-v19/src/os/win/pa_x86_plain_converters.c \
	portaudio-v19/src/os/win/pa_x86_plain_converters.h \
	portaudio-v19/src/SConscript \
	portaudio-v19/test/CMakeLists.txt \
	portaudio-v19/testcvs/changeme.txt \
	portaudio-v19/test/pa_minlat.c \
	portaudio-v19/test/patest1.c \
	portaudio-v19/test/patest_buffer.c \
	portaudio-v19/test/patest_callbackstop.c \
	portaudio-v19/test/patest_clip.c \
	portaudio-v19/test/patest_converters.c \
	portaudio-v19/test/patest_dither.c \
	portaudio-v19/test/patest_dsound_find_best_latency_params.c \
	portaudio-v19/test/patest_dsound_low_level_latency_params.c \
	portaudio-v19/test/patest_dsound_surround.c \
	portaudio-v19/test/patest_hang.c \
	portaudio-v19/test/patest_in_overflow.c \
	portaudio-v19/test/patest_jack_wasapi.c \
	portaudio-v19/test/patest_latency.c \
	portaudio-v19/test/patest_leftright.c \
	portaudio-v19/test/patest_longsine.c \
	portaudio-v19/test/patest_many.c \
	portaudio-v19/test/patest_maxsines.c \
	portaudio-v19/test/patest_mono.c \
	portaudio-v19/test/patest_multi_sine.c \
	portaudio-v19/test/patest_out_underflow.c \
	portaudio-v19/test/patest_prime.c \
	portaudio-v19/test/patest_read_record.c \
	portaudio-v19/test/patest_ringmix.c \
	portaudio-v19/test/patest_sine8.c \
	portaudio-v19/test/patest_sine_channelmaps.c \
	portaudio-v19/test/patest_sine_formats.c \
	portaudio-v19/test/patest_sine_srate.c \
	portaudio-v19/test/patest_sine_time.c \
	portaudio-v19/test/patest_start_stop.c \
	portaudio-v19/test/patest_stop.c \
	portaudio-v19/test/patest_stop_playout.c \
	portaudio-v19/test/patest_suggested_vs_streaminfo_latency.c \
	portaudio-v19/test/patest_suggested_vs_streaminfo_latency.py \
	portaudio-v19/test/patest_sync.c \
	portaudio-v19/test/patest_timing.c \
	portaudio-v19/test/patest_toomanysines.c \
	portaudio-v19/test/patest_two_rates.c \
	portaudio-v19/test/patest_underflow.c \
	portaudio-v19/test/patest_wire.c \
	portaudio-v19/test/patest_wmme_find_best_latency_params.c \
	portaudio-v19/test/patest_wmme_low_level_latency_params.c \
	portaudio-v19/test/patest_write_stop.c \
	portaudio-v19/test/README.txt \
	portaudio-v19/wasapi-fix.patch \
	portaudio-v19/wasapi-loopback.patch \
	$(NULL)
