EXTRA_DIST += \
	libvamp/build/Doxyfile \
	libvamp/build/libvamp-hostsdk.la.in \
	libvamp/build/libvamp-sdk.la.in \
	libvamp/build/Makefile.mingw32 \
	libvamp/build/Makefile.osx \
	libvamp/build/Makefile.osx.106 \
	libvamp/build/README.linux \
	libvamp/build/README.msvc \
	libvamp/build/README.osx \
	libvamp/build/update-version.sh \
	libvamp/build/VampExamplePlugins.sln \
	libvamp/build/VampExamplePlugins.vcproj \
	libvamp/build/VampExamplePlugins.vcxproj \
	libvamp/build/VampHostSDK.sln \
	libvamp/build/VampHostSDK.vcproj \
	libvamp/build/VampHostSDK.vcxproj \
	libvamp/build/vamp-plugin.list \
	libvamp/build/vamp-plugin.map \
	libvamp/build/VampPluginSDK.sln \
	libvamp/build/VampPluginSDK.vcproj \
	libvamp/build/VampPluginSDK.vcxproj \
	libvamp/CHANGELOG \
	libvamp/configure \
	libvamp/configure.ac \
	libvamp/COPYING \
	libvamp/examples/AmplitudeFollower.cpp \
	libvamp/examples/AmplitudeFollower.h \
	libvamp/examples/FixedTempoEstimator.cpp \
	libvamp/examples/FixedTempoEstimator.h \
	libvamp/examples/PercussionOnsetDetector.cpp \
	libvamp/examples/PercussionOnsetDetector.h \
	libvamp/examples/plugins.cpp \
	libvamp/examples/PowerSpectrum.cpp \
	libvamp/examples/PowerSpectrum.h \
	libvamp/examples/SpectralCentroid.cpp \
	libvamp/examples/SpectralCentroid.h \
	libvamp/examples/vamp-example-plugins.cat \
	libvamp/examples/vamp-example-plugins.n3 \
	libvamp/examples/ZeroCrossing.cpp \
	libvamp/examples/ZeroCrossing.h \
	libvamp/fix-all-target.patch \
	libvamp/fix-linkage-against-dl.patch \
	libvamp/host/system.h \
	libvamp/host/vamp-simple-host.cpp \
	libvamp/INSTALL \
	libvamp/Makefile.in \
	libvamp/pkgconfig/vamp-hostsdk.pc.in \
	libvamp/pkgconfig/vamp.pc.in \
	libvamp/pkgconfig/vamp-sdk.pc.in \
	libvamp/rdf/doc/glance.htm \
	libvamp/rdf/doc/vamp.html \
	libvamp/rdf/doc/vamp.pl \
	libvamp/rdf/generator/vamp-rdf-template-generator.cpp \
	libvamp/rdf/README \
	libvamp/rdf/ToDo \
	libvamp/rdf/vamp.n3 \
	libvamp/rdf/vamp.rdf \
	libvamp/README \
	libvamp/README.compat \
	libvamp/skeleton/Makefile.skeleton \
	libvamp/skeleton/MyPlugin.cpp \
	libvamp/skeleton/MyPlugin.h \
	libvamp/skeleton/plugins.cpp \
	libvamp/skeleton/vamp-plugin.list \
	libvamp/skeleton/vamp-plugin.map \
	libvamp/src/doc-overview \
	libvamp/src/vamp-hostsdk/acsymbols.c \
	libvamp/src/vamp-hostsdk/PluginBufferingAdapter.cpp \
	libvamp/src/vamp-hostsdk/PluginChannelAdapter.cpp \
	libvamp/src/vamp-hostsdk/PluginHostAdapter.cpp \
	libvamp/src/vamp-hostsdk/PluginInputDomainAdapter.cpp \
	libvamp/src/vamp-hostsdk/PluginLoader.cpp \
	libvamp/src/vamp-hostsdk/PluginSummarisingAdapter.cpp \
	libvamp/src/vamp-hostsdk/PluginWrapper.cpp \
	libvamp/src/vamp-hostsdk/RealTime.cpp \
	libvamp/src/vamp-hostsdk/Window.h \
	libvamp/src/vamp-sdk/acsymbols.c \
	libvamp/src/vamp-sdk/FFT.cpp \
	libvamp/src/vamp-sdk/FFTimpl.cpp \
	libvamp/src/vamp-sdk/PluginAdapter.cpp \
	libvamp/src/vamp-sdk/RealTime.cpp \
	libvamp/vamp-hostsdk/hostguard.h \
	libvamp/vamp-hostsdk/PluginBase.h \
	libvamp/vamp-hostsdk/PluginBufferingAdapter.h \
	libvamp/vamp-hostsdk/PluginChannelAdapter.h \
	libvamp/vamp-hostsdk/Plugin.h \
	libvamp/vamp-hostsdk/PluginHostAdapter.h \
	libvamp/vamp-hostsdk/PluginInputDomainAdapter.h \
	libvamp/vamp-hostsdk/PluginLoader.h \
	libvamp/vamp-hostsdk/PluginSummarisingAdapter.h \
	libvamp/vamp-hostsdk/PluginWrapper.h \
	libvamp/vamp-hostsdk/RealTime.h \
	libvamp/vamp-hostsdk/vamp-hostsdk.h \
	libvamp/vamp-sdk/FFT.h \
	libvamp/vamp-sdk/plugguard.h \
	libvamp/vamp-sdk/PluginAdapter.h \
	libvamp/vamp-sdk/PluginBase.h \
	libvamp/vamp-sdk/Plugin.h \
	libvamp/vamp-sdk/RealTime.h \
	libvamp/vamp-sdk/vamp-sdk.h \
	libvamp/vamp/vamp.h \
	$(NULL)
