.TH SNDFILE-METADATA-GET 1 "October 6, 2009"
.SH NAME
sndfile-metadata-get \- retrieve metadata from a sound file
.br
sndfile-metadata-set \- set metadata in a sound file
.SH SYNOPSIS
.B sndfile-metadata-get
.RI "[options] file"
.br
.B sndfile-metadata-set
.RI "[options] file"
.br
.B sndfile-metadata-set
.RI "[options] input-file output-file"

.SH DESCRIPTION
sndfile-metadata-get and sndfile-metadata-set use libsndfile
(http://www.mega-nerd.com/libsndfile/) to retrieve metadata from or set metadata
in a sound file.

Run "sndfile\-metadata\-get \-\-help" or "sndfile\-metadata\-set \-\-help" for
more information

.SH AUTHOR
This manual page was written by Erik de Castro Lopo <erikd@mega-nerd.com>.

