.de EX
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 1
.if t .sp .5
..
.TH SNDFILE-PLAY 1 "July 28, 2002"
.SH NAME
sndfile-play \- play a sound file
.SH SYNOPSIS
.B sndfile-play
.RI file
.SH DESCRIPTION
sndfile-play plays the specified sound file using :
.EX
ALSA on Linux
/dev/dsp on systems supporting OSS (including Linux)
/dev/audio on Sun Solaris
CoreAudio on Apple MacOSX
waveOut on Microsoft Win32
.EE
sndfile-play uses libsndfile (http://www.mega-nerd.com/libsndfile/)
to read the file.
.SH AUTHOR
This manual page was originally written by Joshua Haberman 
<joshua@debian.org>, for the Debian GNU/Linux system (but may be used by 
others). Further additions have been made by Erik de Castro Lopo 
<erikd@mega-nerd.com>.

