.TH SNDFILE-INFO 1 "July 28, 2002"
.SH NAME
sndfile-info \- display information about a sound file
.SH SYNOPSIS
.B sndfile-info
.RI file
.SH DESCRIPTION
sndfile-info will display basic information about a sound file such as
its format, its sample rate, and the number of channels. This information
is obtained using libsndfile (http://www.mega-nerd.com/libsndfile/).
.SH AUTHOR
This manual page was originally written by Joshua Haberman 
<joshua@debian.org>, for the Debian GNU/Linux system (but may be used by 
others). Further additions have been made by Erik de Castro Lopo 
<erikd@mega-nerd.com>.

