.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\" roqet.1 - Rasqal RDF query test program
.\"
.\" $Id: roqet.1,v 1.1 2008-07-08 10:47:07 larsl Exp $
.\"
.\" Copyright (C) 2004-2008 David Beckett - http://www.dajobe.org/
.\" Copyright (C) 2004-2005 University of Bristol - http://www.bristol.ac.uk/
.\"
.TH roqet 1 "2008-06-22"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
roqet \- Rasqal RDF query utility
.SH SYNOPSIS
.B roqet
.RB [ OPTIONS ]
.IR "<query-URI>"
.IR "[base-URI]"
.br
.B roqet
.RB [ OPTIONS ] -e
.IR "query-string"
.IR "[base-URI]"
.SH EXAMPLE
.nf
.B roqet example.sparql
.br
.B roqet -q -i rdql x.rdql http://example.org/base/
.br
.B roqet -i sparql -r xml http://example.org/query.rq
.br
.SH DESCRIPTION
The
.B roqet
utility allows querying of RDF content using the
.B Rasqal
RDF query library, printing the results in variable bindings,
RDF graph or boolean format.  The query is read from \fIquery-URI\fR and
the optional \fIbase-URI\fR is used as the base URI of the query if present.
.SH MAIN OPTIONS
roqet uses the usual GNU command line syntax, with long
options starting with two dashes (`-') if supported by the
getopt_long function.  Otherwise only the short options are available.
.TP
.B \-e, \-\-exec QUERY
Execute the query in the argument
.I QUERY
instead of reading the query from a URI (when -e is not given).
.TP
.B \-i, \-\-input LANGUAGE
Set the input query
.I LANGUAGE
to one of'sparql' (SPARQL Query Language for RDF, default)
or 'rdql' (RDF Data Query Language).   The list of
supported languages is given in the help summary given by \-h.
.TP
.B \-r, \-\-results FORMAT
Set the query results format.
.IP
For variable bindings, the values of
.I FORMAT
vary upon what Rasqal supports but include 'simple'
for a simple text format (default), 'xml'
for the SPARQL Query Results XML format
and 'json' for a JSON version of the results.
.IP
For RDF graph results, the values of
.I FORMAT
are 'ntriples' (N-Triples, default), 'rdfxml-abbrev'
(RDF/XML Abbreviated), 'rdfxml' (RDF/XML), 'turtle' (Turtle), 'json'
(RDF/JSON resource centric), 'json-triples' (RDF/JSON triples)
or 'rss-1.0' (RSS 1.0, also an RDF/XML syntax).
.IP
The exact list of formats depends on what libraptor(3) was built with
but is given correct in the usage message with \-h.
.SH OTHER OPTIONS
.TP
.B \-c, \-\-count
Only count the triples and produce no other output.
.TP
.B \-D, \-\-data URI
Add RDF data source URI (not a named graph)
.TP
.B \-d, \-\-dump\-query FORMAT
Print the parsed query out in a given
.I FORMAT
one of 'debug', 'structure' or 'sparql'
.TP
.B \-f, \-\-feature NAME(=VALUE)
Set query feature
.I NAME
to the
.I VALUE
or integer 1 if omitted.
The known features can be shown with \fB-f help\fP or \fB--feature help\fP.
.TP
.B \-G, \-\-named URI
Add RDF data source URI (named graph)
.TP
.B \-h, \-\-help
Show a summary of the options.
.TP
.B \-n, \-\-dryrun
Prepare the query but do not execute it.
.TP
.B \-q, \-\-quiet
No extra information messages.
.TP
.B \-s, \-\-source URI
Ad RDF data source URI (named graph))
.I URI
by adding it to the list of query data source URIs.
.I FORMAT
to 'simple' (default) or 'xml' (an experimental XML format)
.TP
.B \-v, \-\-version
Print the rasqal library version and exit.
.TP
.B \-w, \-\-walk-query
Walk the query and display it using the API.
.SH "CONFORMING TO"
\fISPARQL Query Language for RDF\fR, 
Eric Prud'hommeaux and Andy Seaborne (eds), W3C Recommendation, 15 January 2008.
.UR http://www.w3.org/TR/2008/REC-rdf-sparql-query-20080115/
http://www.w3.org/TR/2008/REC-rdf-sparql-query-20080115/
.UE
.LP
\fISPARQL Query Results XML Format\fR, 
Jeen Broekstra and Dave Beckett (eds), W3C Recommendation, 15 January 2008.
.UR http://www.w3.org/TR/2008/REC-rdf-sparql-XMLres-20080115/
http://www.w3.org/TR/2008/REC-rdf-sparql-XMLres-20080115/
.UE
.LP
\fIRDQL - A Query Language for RDF\fR, Andy Seaborne,
W3C Member Submission 9 January 2004
.UR http://www.w3.org/Submission/2004/SUBM-RDQL-20040109/
http://www.w3.org/Submission/2004/SUBM-RDQL-20040109/
.UE
.SH SEE ALSO
.BR librasqal(3), rasqal-config(1), libraptor(3)
.SH CHANGES
.br
.SH AUTHOR
Dave Beckett - 
.UR http://www.dajobe.org/
http://www.dajobe.org/
.UE
.br
