.TH "Utility functions" 3 "6 Jul 2008" "Version 0.6.0" "SLV2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Utility functions \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBslv2_uri_to_path\fP (const char *uri)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* slv2_uri_to_path (const char * uri)"
.PP
Convert a full URI (eg file://foo/bar/baz.ttl) to a local path (e.g. 
.PP
/foo/bar/baz.ttl).
.PP
Return value is shared and must not be deleted by caller. 
.PP
\fBReturns:\fP
.RS 4
\fIuri\fP converted to a path, or NULL on failure (URI is not local). 
.RE
.PP

