.\" Process this file with
.\" groff -man -Tascii audacity.1
.\"
.TH audacity 1
.SH NAME
audacity \- Graphical cross-platform audio editor
.SH SYNOPSIS
.B audacity
\-help
.br
.B audacity
\-version
.br

.B audacity
[\-blocksize nnn] \-test
.br
.B audacity
[\-blocksize nnn] [
.I AUDIO-FILE
]
.B ...
.SH DESCRIPTION
.B Audacity
is a graphical audio editor.  This man page does not
describe all of the features of Audacity or how to use
it; for this, see the html documentation that came with
the program, which should be accessible from the Help
menu.  This man page describes the Unix-specific
features, including special files and environment variables.

Audacity currently uses
.B libsndfile
to open many uncompressed audio formats such as WAV,
AIFF, and AU, and it can also be linked to
.B libmad,
.B libvorbis,
and
.B libflac,
to provide support for opening MP2/3, Ogg Vorbis, and FLAC files,
respectively.
.B LAME, libvorbis, libflac
and
.B libtwolame
provide facilities to export files to all these formats as well.

Audacity is primarily an interactive, graphical editor, not a batch-processing
tool. Whilst there is a basic batch processing tool it is experimental and 
incomplete. If you need to batch-process audio or do simple edits
from the command line, using 
.B sox
or
.B ecasound
driven by a bash script will be much more powerful than audacity.

.SH OPTIONS
.TP 10
\fB\-help\fR
display a brief list of command line options
.TP 10
\fB\-version\fR
display the audacity version number
.TP 10
\fB\-test\fR
run self diagnostics tests (only present in development builds)
.TP 10
\fB\-blocksize nnn\fR
set the audacity block size for writing files to disk to nnn bytes

.SH FILES
.I ~/.audacity\-data/audacity.cfg
.RS
Per user configuration file.
.RE

.I /var/tmp/audacity\-<user>/
.RS
Default location of Audacity's temp directory, where <user> is your
username.  If this location is not suitable (not enough space in
/var/tmp, for example), you should change the temp directory in
the Preferences and restart Audacity.  Audacity is a disk-based
editor, so the temp directory is very important: it should always
be on a fast (local) disk with lots of free space.

Note that older versions of Audacity put the temp directory inside
of the user's home directory.  This is undesirable on many systems,
and using some directory in /tmp is recommended.

On many modern Linux systems all files in /tmp/ will be deleted 
each time the system boots up, which makes recovering a recording
that was going on when the system crashed much harder. This is why
the default is to use a directory in /var/tmp/ which will not
normally be deleted by the system. Open the Preferences to check.
.RE
.SH SEARCH PATH
When looking for plug-ins, help files, localization files, or other
configuration files, Audacity searches the following locations, in
this order:

.I AUDACITY_PATH
.RS
Any directories in the 
.I AUDACITY_PATH 
environment variable will be searched before anywhere else.
.RE

.I .
.RS
The current working directory when Audacity is started.
.RE

.I ~/.audacity-data/Plug-Ins

.I <prefix>/share/audacity
.RS
The system-wide Audacity directory, where <prefix> is usually
/usr or /usr/local, depending on where the program was installed.
.RE

.I <prefix>/share/doc/audacity
.RS
The system-wide Audacity documentation directory, where <prefix> is usually
/usr or /usr/local, depending on where the program was installed.
.RE

For localization files in particular (i.e. translations of Audacity
into other languages), Audacity also searches
.I <prefix>/share/locale

.SH PLUG\-INS

Audacity supports two types of plug-ins on Unix: LADSPA and Nyquist
plug-ins.  These are generally placed in a directory called 
.I plug\-ins 
somewhere on the search path (see above).

LADSPA plug-ins can either be in the plug-ins directory, or alternatively
in a 
.I ladspa 
directory on the search path if you choose to create one.  Audacity will
also search the directories in the 
.I LADSPA_PATH 
environment variable for additional LADSPA plug-ins.

Nyquist plug-ins can either be in the plug-ins directory, or alternatively
in a 
.I nyquist
directory on the search path if you choose to create one.

.SH VERSION
This man page documents audacity version 1.3.5

.SH LICENSE

Audacity is distributed under the GPL, however some of the libraries
it links to are distributed under other free licenses, including the
LGPL and BSD licenses.

.SH BUGS

For details of known problems, see the release notes and the audacity wiki:
.br
http://wiki.audacityteam.org/wiki/Known_Issues

To report a bug, see the instructions at
.br
http://wiki.audacityteam.org/wiki/Reporting_Bugs

.SH AUTHORS
Project leaders include Dominic Mazzoni, Matt Brubeck,
James Crook, Vaughan Johnson, Leland Lucius, and Markus Meyer,
but dozens of others have contributed, and Audacity would not
be possible without wxWidgets, libsndfile, and many of
the other libraries it is built upon.  For the most recent list
of contributors and current email addresses, see our website:

http://www.audacityteam.org/about/credits/

.\" arch-tag: 204d77ab-73cf-42b1-b5bd-e6f07e660496

