.\" Process this file with
.\" groff -man -Tascii audacity.1
.\"
.TH audacity 1
.SH NAME
audacity \- audio editor
.SH SYNOPSIS
.B audacity
[
.I AUDIO-FILE
]

.SH DESCRIPTION
.B Audacity
is a graphical audio editor. It generally does not support
command line options, outside of opening files. 

Documentation and support can be found on 
https://support.audacityteam.org/

The manual for Audacity 3.x can be found on
https://manual.audacityteam.org/

.SH LICENSE
Audacity is distributed under the GPL. Details can be
found in the LICENSE.txt, or at 
.br
https://github.com/audacity/audacity/blob/master/LICENSE.txt

.SH BUGS
For a list of known bugs or to report your own, see
.br
https://github.com/audacity/audacity/issues

.SH AUTHORS
Audacity is developed by Muse Group and contributors. 
For details, open Audacity and go to Help > About Audacity.