#  test_seeking - Seeking tester for libFLAC
#  Copyright (C) 2004-2009  Josh Coalson
#  Copyright (C) 2011-2014  Xiph.Org Foundation
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#
# GNU makefile
#

topdir = ../..
libdir = $(topdir)/objs/$(BUILD)/lib

PROGRAM_NAME = test_seeking

INCLUDES = -I../libFLAC/include -I$(topdir)/include

ifeq ($(OS),Darwin)
    EXPLICIT_LIBS = $(libdir)/libFLAC.a $(OGG_EXPLICIT_LIBS) -lm
else
ifeq ($(findstring Windows,$(OS)),Windows)
    LIBS = -lFLAC -lwin_utf8_io $(OGG_LIBS) -lm
else
    LIBS = -lFLAC $(OGG_LIBS) -lm
endif
endif

SRCS_C = \
	main.c

include $(topdir)/build/exe.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
