name: Enhancement request
description: Request an existing feature to be made better, or a new feature
labels: ["Enhancement Request"]
body:
  - type: textarea
    id: whatfor
    attributes:
      label: Problem to be solved
      description: What problem would your idea solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: Describe your idea in a few sentences.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Prior art
      description: Have you run into this problem with other apps? How did they solve it? You can paste screenshots. 
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else of note
    validations:
      required: false
  - type: markdown
    attributes:
      value: >
        Please note that Audacity is currently undergoing major restructuring. See the [Roadmap](https://github.com/audacity/audacity/wiki/Roadmap)
        for further info. Features outside the roadmap may be delayed or postponed significantly. 