name: Plugin issue
description: Report problems or crashes with a plugin
title: "[Plugin issue] "
labels: ["plugins"]
type: "bug"
body:
  - type: input
    id: plugin
    attributes:
      label: Plugin
      description: What is the name of the plugin?
    validations:
      required: true
  - type: dropdown
    id: pluginfmt
    attributes:
      label: Plugin Format
      description: If the plugin is available in multiple formats, tell us the version you're using. 
      options:
        - VST3
        - VST2
        - LV2
        - LADSPA
        - Audio Unit
        - Nyquist
        - Vamp
        - Other
    validations:
      required: true
  - type: input
    id: pluginsrc
    attributes:
      label: Plugin source
      description: Where did you get your plugin from?
      placeholder: https://example.com
  - type: textarea
    id: desc
    attributes:
      label: Bug description
      description: A more detailled description of the bug
      placeholder: Context for the bug that didn't fit in the title
    validations:
      required: false
  - type: textarea
    id: str
    attributes:
      label: Steps to reproduce
      description: Please provide step-by-step instructions to reproduce this bug 
      placeholder: |
        1. go to ...
        2. then click on ...
        3. then ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen when you do these things?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What are you actually seeing?
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Audacity Version
      description: What version of Audacity are you running?
      options:
        - current master / alpha / nightly build
        - latest beta
        - latest stable version (from audacityteam.org/download)
        - stable version (from a Linux repository)
        - other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: What OS does this bug occur on?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Other
        - OS independent
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      description: What architecture are you running on?
      multiple: true
      options:
        - 64 bit Intel/AMD processors 
        - 32 bit Intel/AMD processors 
        - Apple Silicon (M1, M2, ...)
        - Other
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Further information which may be relevant to this bug
      placeholder: Sound card, commit ID, Screenshots, trial vs paid version, etc.
  - type: markdown
    attributes:
      value: >
        Please note that Audacity is currently undergoing major restructuring. See the [Roadmap](https://github.com/audacity/audacity/wiki/Roadmap)
        for further info. Bug fixes may be delayed or postponed significantly. 