#ifndef HAVE_SHARED_BUTTONS
#ifdef USE_AQUA_THEME
#include "Aqua/UpButtonSquare.xpm"
#include "Aqua/DownButtonSquare.xpm"
#include "Aqua/HiliteButtonSquare.xpm"
//#include "Aqua/Up.xpm"
//#include "Aqua/Down.xpm"
//#include "Aqua/Hilite.xpm"
#include "Aqua/SliderThumb.xpm"
#include "Aqua/Slider.xpm"
#else
#include "ControlButtons/UpButton.xpm"
#include "ControlButtons/DownButton.xpm"
#include "ControlButtons/HiliteButton.xpm"
#endif
#endif

#include "ControlButtons/FFwdAlpha.xpm"
#include "ControlButtons/FFwdDisabled.xpm"
#include "ControlButtons/FFwd.xpm"
#include "ControlButtons/PlayAlpha.xpm"
#include "ControlButtons/PlayDisabled.xpm"
#include "ControlButtons/Play.xpm"
#include "ControlButtons/Loop.xpm"
#include "ControlButtons/LoopDisabled.xpm"
#include "ControlButtons/LoopAlpha.xpm"
#include "ControlButtons/RecordAlpha.xpm"
#include "ControlButtons/RecordDisabled.xpm"
#include "ControlButtons/Record.xpm"
#include "ControlButtons/CleanSpeechAlpha.xpm"
#include "ControlButtons/CleanSpeechDisabled.xpm"
#include "ControlButtons/CleanSpeech.xpm"
#include "ControlButtons/RewindAlpha.xpm"
#include "ControlButtons/RewindDisabled.xpm"
#include "ControlButtons/Rewind.xpm"
#include "ControlButtons/StopAlpha.xpm"
#include "ControlButtons/StopDisabled.xpm"
#include "ControlButtons/Stop.xpm"
#include "ControlButtons/Pause.xpm"
#include "ControlButtons/PauseDisabled.xpm"
#include "ControlButtons/PauseAlpha.xpm"
