set(TREEVIEW_SRC
    ${CMAKE_CURRENT_LIST_DIR}/qquicktreemodeladaptor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qquicktreemodeladaptor_p.h
    ${CMAKE_CURRENT_LIST_DIR}/qquickrangemodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qquickrangemodel_p.h
    ${CMAKE_CURRENT_LIST_DIR}/qquickrangemodel_p_p.h
    ${CMAKE_CURRENT_LIST_DIR}/qquickwheelarea.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qquickwheelarea_p.h
    ${CMAKE_CURRENT_LIST_DIR}/qquickabstractstyle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qquickabstractstyle_p.h
    ${CMAKE_CURRENT_LIST_DIR}/qquickpadding_p.h
    ${CMAKE_CURRENT_LIST_DIR}/qquickselectionmode_p.h
)
