#
# GNU makefile
#

topdir = ../../..

LIB_NAME = libgetopt
INCLUDES = -I$(topdir)/include

SRCS_C = \
	getopt.c \
	getopt1.c

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
