# Only extended types with identical lexical rep and datatypes can be = .
# $Id: extendedType-eq-pass.rq,v 1.1 2008-07-08 10:46:41 larsl Exp $

PREFIX loc: <http://www.w3.org/2001/sw/DataAccess/tests/data/ValueTesting/extendedType-0#>
PREFIX wgs: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX air: <http://www.daml.org/2001/10/html/airport-ont#>
#PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
#SELECT ?a1 (xsd:float(xsd:string(?rot1))-5.5) ?a2 
SELECT ?a1 ?a2
 WHERE {?a1 air:name ?name1 ;
            loc:location ?l1 .
        ?l1 loc:rotational ?rot1 .
        ?a2 air:name ?name2 ;
            loc:location ?l2 .
        ?l2 loc:rotational ?rot2 .
        FILTER (?rot1 = ?rot2)}
#        FILTER (str(?rot1) = "-7420507.1")}
