# Test graph match on extended type.
# $Id: extendedType-graph.rq,v 1.1 2008-07-08 10:46:41 larsl Exp $

PREFIX loc: <http://www.w3.org/2001/sw/DataAccess/tests/data/ValueTesting/extendedType-0#>
PREFIX air: <http://www.daml.org/2001/10/html/airport-ont#>
SELECT ?a1
 WHERE {?a1 air:name ?name1 ;
            loc:location ?l1 .
        ?l1 loc:rotational "-7420507.1"^^loc:ECEF_X }
