# Negative test: product of type promotion within the xsd:decimal type tree.
# $Id: typePromotion-decimal-decimal-fail.rq,v 1.1 2008-07-08 10:46:43 larsl Exp $

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?one ?two
 WHERE { ?one rdfs:value ?oneL .
         ?two rdfs:value ?twoL .
         FILTER ( datatype(?oneL) = xsd:unsignedByte && 
                  datatype(?twoL) = xsd:unsignedShort && 
                  datatype(?oneL + ?twoL) = xsd:unsignedShort ) }
