(translate "stkrev")
(translate "stkpitshift")
(translate "stkchorus")
(translate "instrbow")
(translate "instrbowedfreq")
(translate "instrbanded")
(translate "instrmandolin")
(translate "instrsitar")
(translate "instrmodalbar")                   
(translate "instrflute")
(translate "instrflutefreq")
(translate "instrfluteall")

