language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
env:
  - FLAGS=""
  - FLAGS="--debug"
  - FLAGS="        --no-posix"
  - FLAGS="--debug --no-posix"
  - FLAGS="                   --static --static-progs --no-shared"
  - FLAGS="--debug            --static --static-progs --no-shared"
  - FLAGS="        --no-posix --static --static-progs --no-shared"
  - FLAGS="--debug --no-posix --static --static-progs --no-shared"
matrix:
  exclude:
    - os: osx
      env: FLAGS="                   --static --static-progs --no-shared"
    - os: osx
      env: FLAGS="--debug            --static --static-progs --no-shared"
    - os: osx
      env: FLAGS="        --no-posix --static --static-progs --no-shared"
    - os: osx
      env: FLAGS="--debug --no-posix --static --static-progs --no-shared"
    - os: osx
      compiler: gcc
script:
  - ./waf configure --test --no-coverage --strict $FLAGS
  - ./waf build
  - ./waf test
