.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\" rapper.1 - Raptor RDF parsing and serializing utility manual page
.\"
.\" Copyright (C) 2002-2008 David Beckett - http://www.dajobe.org/
.\" Copyright (C) 2002-2005 University of Bristol - http://www.bristol.ac.uk/
.\"
.TH rapper 1 "2007-08-19"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
rapper \- Raptor RDF parsing and serializing utility
.SH SYNOPSIS
.B rapper
.RB [ OPTIONS ]
.IR "INPUT-URI"
.IR "[INPUT-BASE-URI]"
.SH EXAMPLE
.nf
.B rapper -o ntriples http://planetrdf.com/guide/rss.rdf
.br
.B rapper -i rss-tag-soup -o rss-1.0 pile-of-rss.xml http://example.org/base/
.br
.B rapper --count http://example.org/index.rdf
.SH DESCRIPTION
The
.B rapper
utility allows parsing of RDF content by the
.B Raptor
RDF parser toolkit emitting the results as RDF triples in
a choice of syntaxes.  The \fIINPUT-URI\fR can be a file name, '-'
for standard input or if Raptor is built with a WWW retrieval
library, a general URI.  The optional \fIINPUT-BASE-URI\fR is used as the
document parser base URI if present otherwise defaults to the \IINPUT-URI\fR.
A value of '-' means no base URI.
.SH OPTIONS
rapper uses the usual GNU command line syntax, with long
options starting with two dashes (`-') if supported by the
getopt_long function.  Otherwise the short options are only available.
.TP
.B \-h, \-\-help
Show a summary of the options.
.TP
.B \-i, \-\-input FORMAT
Set the input
.I FORMAT
to one of 'rdfxml' (RDF/XML, default), 'ntriples'
(N-Triples, see below), 'turtle' (Turtle, see below)
or 'rss-tag-soup' (RSS Tag Soup).  The RSS Tag Soup parser
can turn the many XML RSS formats and Atom 0.3 into RDF triples.
.IP
The list of
parsers depends on how libraptor(3) was built.  The list of
supported parsers is given in the help summary given by \-h.
.TP
.B \-I, \-\-input-uri URI
Set the input/parser base
.I URI
or use value '-' for no base.
The default is the INPUT-URI argument value.
.TP
.B \-o, \-\-output FORMAT
Set the output
.I FORMAT
to 'ntriples' (N-Triples, default), 'rdfxml' (RDF/XML), 'rdfxml-abbrev'
(RDF/XML with abbreviations) or 'rss-1.0' (RSS 1.0, also an RDF/XML syntax).
.IP
The list of
serializers depends on how libraptor(3) was built.  The list of
supported serializers is given in the help summary given by \-h.
.TP
.B \-O, \-\-output-uri URI
Set the output/serializer base
.I URI
or use value '-' for no base.
The default is the input base uri, either set by the argument
INPUT-BASE-URI or via options
.B \-I, \-\-input-uri URI
.TP
.B \-c, \-\-count
Only count the triples and produce no other output.
.TP
.B \-e, \-\-ignore-errors
Ignore errors, do not emit the messages and try to continue parsing.
.TP
.B \-f, \-\-feature FEATURE[=VALUE]
Set a parser or serializer feature
.I FEATURE
to a value, or to 1 if
.I VALUE
is omitted,
Use \-f help to get lists of valid parser and serializer features.
.IP
If the form \-f 'xmlns:\fIprefix\fP=\(dq\fIuri\fP\(dq' is used,
the prefix and namespace uri given will be set for serializing.
The syntax matches XML in that either or both of \fIprefix\fP
or \fIuri\fP can be omitted.
.TP
.B \-g, \-\-guess
Guess the parser to use from the source-URI rather than use
the \-i FORMAT.
.TP
.B \-q, \-\-quiet
No extra information messages.
.TP
.B \-r, \-\-replace-newlines
Replace newlines in multi-line literals with spaces.
.TP
.B \-s, \-\-scan
Scan for <rdf:RDF> element in the RDF/XML source content.
.TP
.B \-\-show-graphs
Print graph names (URIs) as they are seen in the input.  This only
has a meaning for parsers that support graph names such as the TRiG parser.
.TP
.B \-\-show-namespaces
Print namespaces as they are seen in the input.
.TP
.B \-t, \-\-trace
Print URIs retrieved during parsing.  Especially useful for 
monitoring what the guess and GRDDL parsers are doing.
.TP
.B \-w, \-\-ignore-warnings
Ignore warnings, do not emit the messages.
.TP
.B \-v, \-\-version
Print the raptor version and exit.
.SH "EXAMPLES"
.br
.B rapper -q -i ntriples -o rdfxml -f 'xmlns:rss="http://purl.org/rss/1.0/"' -f 'xmlns:ex="http://example.org/"' tests/test.nt
.br
.B rapper -q -o rdfxml -f 'xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"' tests/rdf-schema.rdf 'http://www.w3.org/2000/01/rdf-schema#'
.SH "CONFORMING TO"
\fIRDF/XML Syntax (Revised)\fR,
W3C Recommendation,
.UR http://www.w3.org/TR/rdf-syntax-grammar/
http://www.w3.org/TR/rdf-syntax-grammar/
.UE

\fIN-Triples\fR, in \fIRDF Test Cases\fR, Jan Grant and Dave Beckett (eds.),
W3C Recommendation,
.UR http://www.w3.org/TR/rdf-testcases/#ntriples
http://www.w3.org/TR/rdf-testcases/#ntriples
.UE

\fITurtle Terse RDF Triple Language\fR, Dave Beckett,
.UR http://www.dajobe.org/2004/01/turtle/
http://www.dajobe.org/2004/01/turtle/
.UE

\fIRDFA in XHTML: Syntax and Processing\fR, Ben Adida, Mark Birbeck,
Shane McCarron and Steven Pemberton (eds.),
W3C Candidate Recommendation, 20 June 2008
.UR http://www.w3.org/TR/2008/CR-rdfa-syntax-20080620/
http://www.w3.org/TR/2008/CR-rdfa-syntax-20080620/
.UE

\fIRDF Site Summary (RSS) 1.0\fR, 2000-12-06
.UR http://purl.org/rss/1.0/spec
http://purl.org/rss/1.0/spec
.UE
.SH SEE ALSO
.BR libraptor(3), raptor-config(1)
.SH CHANGES
.SS 1.4.16
Added -I/--input-uri and -O/--output-uri to set the input and output
(parser and serializer) base URIs separately.
.SS 1.4.15
Added -t/--trace to do URI traces.
.SS 1.4.5
Updated to add serializer rdfxml-abbrev
.SS 1.4.3
Updated potential parser and serializers and described -f for
defining namespaces.
.SS 1.3.0
Added \-f for features.
.br
Added \-g for guessing the parser to use.
.SS 1.1.0
Removed \-a, \-\-assume since rdf:RDF is now always optional.
.br
.SH AUTHOR
Dave Beckett - 
.UR http://www.dajobe.org/
http://www.dajobe.org/
.UE
.br
