SET_THEME_FLAGS(resFlagPaired);
DEFINE_IMAGE(bmpPause, wxImage(16, 16), wxT("Pause"));
DEFINE_IMAGE(bmpPauseDisabled, wxImage(16, 16), wxT("PauseDisabled"));
DEFINE_IMAGE(bmpPlay, wxImage(16, 16), wxT("Play"));
DEFINE_IMAGE(bmpPlayDisabled, wxImage(16, 16), wxT("PlayDisabled"));
DEFINE_IMAGE(bmpLoop, wxImage(16, 16), wxT("Loop"));
DEFINE_IMAGE(bmpLoopDisabled, wxImage(16, 16), wxT("LoopDisabled"));
DEFINE_IMAGE(bmpCutPreview, wxImage(16, 16), wxT("CutPreview"));
DEFINE_IMAGE(bmpCutPreviewDisabled, wxImage(16, 16), wxT("CutPreviewDisabled"));
DEFINE_IMAGE(bmpStop, wxImage(16, 16), wxT("Stop"));
DEFINE_IMAGE(bmpStopDisabled, wxImage(16, 16), wxT("StopDisabled"));
DEFINE_IMAGE(bmpRewind, wxImage(16, 16), wxT("Rewind"));
DEFINE_IMAGE(bmpRewindDisabled, wxImage(16, 16), wxT("RewindDisabled"));
DEFINE_IMAGE(bmpFFwd, wxImage(16, 16), wxT("FFwd"));
DEFINE_IMAGE(bmpFFwdDisabled, wxImage(16, 16), wxT("FFwdDisabled"));
DEFINE_IMAGE(bmpRecord, wxImage(16, 16), wxT("Record"));
DEFINE_IMAGE(bmpRecordDisabled, wxImage(16, 16), wxT("RecordDisabled"));
DEFINE_IMAGE(bmpRecordBeside, wxImage(16, 16), wxT("RecordBeside"));
DEFINE_IMAGE(bmpRecordBesideDisabled, wxImage(16, 16), wxT("RecordBesideDisabled"));
DEFINE_IMAGE(bmpRecordBelow, wxImage(16, 16), wxT("RecordBelow"));
DEFINE_IMAGE(bmpRecordBelowDisabled, wxImage(16, 16), wxT("RecordBelowDisabled"));
DEFINE_IMAGE(bmpScrub, wxImage(18, 16), wxT("Scrub"));
DEFINE_IMAGE(bmpScrubDisabled, wxImage(18, 16), wxT("ScrubDisabled"));
DEFINE_IMAGE(bmpSeek, wxImage(26, 16), wxT("Seek"));
DEFINE_IMAGE(bmpSeekDisabled, wxImage(26, 16), wxT("SeekDisabled"));

SET_THEME_FLAGS(resFlagNewLine);
DEFINE_IMAGE(bmpIBeam, wxImage(27, 27), wxT("IBeam"));
DEFINE_IMAGE(bmpZoom, wxImage(27, 27), wxT("Zoom"));
DEFINE_IMAGE(bmpEnvelope, wxImage(27, 27), wxT("Envelope"));
DEFINE_IMAGE(bmpTimeShift, wxImage(27, 27), wxT("TimeShift"));
DEFINE_IMAGE(bmpDraw, wxImage(27, 27), wxT("Draw"));
DEFINE_IMAGE(bmpMulti, wxImage(27, 27), wxT("Multi"));
DEFINE_IMAGE(bmpMic, wxImage(25, 25), wxT("Mic"));
DEFINE_IMAGE(bmpSpeaker, wxImage(25, 25), wxT("Speaker"));

SET_THEME_FLAGS(resFlagPaired);
DEFINE_IMAGE(bmpZoomFit, wxImage(27, 27), wxT("ZoomFit"));
DEFINE_IMAGE(bmpZoomFitDisabled, wxImage(27, 27), wxT("ZoomFitDisabled"));
DEFINE_IMAGE(bmpZoomIn, wxImage(27, 27), wxT("ZoomIn"));
DEFINE_IMAGE(bmpZoomInDisabled, wxImage(27, 27), wxT("ZoomInDisabled"));
DEFINE_IMAGE(bmpZoomOut, wxImage(27, 27), wxT("ZoomOut"));
DEFINE_IMAGE(bmpZoomOutDisabled, wxImage(27, 27), wxT("ZoomOutDisabled"));
DEFINE_IMAGE(bmpZoomSel, wxImage(27, 27), wxT("ZoomSel"));
DEFINE_IMAGE(bmpZoomSelDisabled, wxImage(27, 27), wxT("ZoomSelDisabled"));
DEFINE_IMAGE(bmpZoomToggle, wxImage(27, 27), wxT("ZoomToggle"));
DEFINE_IMAGE(bmpZoomToggleDisabled, wxImage(27, 27), wxT("ZoomToggleDisabled"));
DEFINE_IMAGE(bmpCut, wxImage(26, 24), wxT("Cut"));
DEFINE_IMAGE(bmpCutDisabled, wxImage(26, 24), wxT("CutDisabled"));
DEFINE_IMAGE(bmpCopy, wxImage(26, 24), wxT("Copy"));
DEFINE_IMAGE(bmpCopyDisabled, wxImage(26, 24), wxT("CopyDisabled"));
DEFINE_IMAGE(bmpPaste, wxImage(26, 24), wxT("Paste"));
DEFINE_IMAGE(bmpPasteDisabled, wxImage(26, 24), wxT("PasteDisabled"));
DEFINE_IMAGE(bmpTrim, wxImage(26, 24), wxT("Trim"));
DEFINE_IMAGE(bmpTrimDisabled, wxImage(26, 24), wxT("TrimDisabled"));
DEFINE_IMAGE(bmpSilence, wxImage(26, 24), wxT("Silence"));
DEFINE_IMAGE(bmpSilenceDisabled, wxImage(26, 24), wxT("SilenceDisabled"));
DEFINE_IMAGE(bmpUndo, wxImage(26, 24), wxT("Undo"));
DEFINE_IMAGE(bmpUndoDisabled, wxImage(26, 24), wxT("UndoDisabled"));
DEFINE_IMAGE(bmpRedo, wxImage(26, 24), wxT("Redo"));
DEFINE_IMAGE(bmpRedoDisabled, wxImage(26, 24), wxT("RedoDisabled"));

SET_THEME_FLAGS(resFlagPaired | resFlagNewLine);
DEFINE_IMAGE(bmpTnStartOn, wxImage(27, 27), wxT("TnStartOn"));
DEFINE_IMAGE(bmpTnStartOnDisabled, wxImage(27, 27), wxT("TnStartOnDisabled"));
DEFINE_IMAGE(bmpTnStartOff, wxImage(27, 27), wxT("TnStartOff"));
DEFINE_IMAGE(bmpTnStartOffDisabled, wxImage(27, 27), wxT("TnStartOffDisabled"));
DEFINE_IMAGE(bmpTnEndOn, wxImage(27, 27), wxT("TnEndOn"));
DEFINE_IMAGE(bmpTnEndOnDisabled, wxImage(27, 27), wxT("TnEndOnDisabled"));
DEFINE_IMAGE(bmpTnEndOff, wxImage(27, 27), wxT("TnEndOff"));
DEFINE_IMAGE(bmpTnEndOffDisabled, wxImage(27, 27), wxT("TnEndOffDisabled"));
DEFINE_IMAGE(bmpTnCalibrate, wxImage(27, 27), wxT("TnCalibrate"));
DEFINE_IMAGE(bmpTnCalibrateDisabled, wxImage(27, 27), wxT("TnCalibrateDisabled"));
DEFINE_IMAGE(bmpTnAutomateSelection, wxImage(27, 27), wxT("TnAutomateSelection"));
DEFINE_IMAGE(bmpTnAutomateSelectionDisabled, wxImage(27, 27), wxT("TnAutomateSelectionDisabled"));
DEFINE_IMAGE(bmpTnMakeTag, wxImage(27, 27), wxT("TnMakeTag"));
DEFINE_IMAGE(bmpTnMakeTagDisabled, wxImage(27, 27), wxT("TnMakeTagDisabled"));
DEFINE_IMAGE(bmpTnSelectSound, wxImage(24, 24), wxT("TnSelectSound"));
DEFINE_IMAGE(bmpTnSelectSoundDisabled, wxImage(24, 24), wxT("TnSelectSoundDisabled"));
DEFINE_IMAGE(bmpTnSelectSilence, wxImage(24, 24), wxT("TnSelectSilence"));
DEFINE_IMAGE(bmpTnSelectSilenceDisabled, wxImage(24, 24), wxT("TnSelectSilenceDisabled"));
DEFINE_IMAGE(bmpOptions, wxImage(24, 24), wxT("Options"));
DEFINE_IMAGE(bmpOptionsDisabled, wxImage(24, 24), wxT("OptionsDisabled"));

SET_THEME_FLAGS(resFlagNone);
DEFINE_IMAGE(bmpLabelGlyph0, wxImage(15, 23), wxT("LabelGlyph0"));
DEFINE_IMAGE(bmpLabelGlyph1, wxImage(15, 23), wxT("LabelGlyph1"));
DEFINE_IMAGE(bmpLabelGlyph2, wxImage(15, 23), wxT("LabelGlyph2"));
DEFINE_IMAGE(bmpLabelGlyph3, wxImage(15, 23), wxT("LabelGlyph3"));
DEFINE_IMAGE(bmpLabelGlyph4, wxImage(15, 23), wxT("LabelGlyph4"));
DEFINE_IMAGE(bmpLabelGlyph5, wxImage(15, 23), wxT("LabelGlyph5"));
DEFINE_IMAGE(bmpLabelGlyph6, wxImage(15, 23), wxT("LabelGlyph6"));
DEFINE_IMAGE(bmpLabelGlyph7, wxImage(15, 23), wxT("LabelGlyph7"));
DEFINE_IMAGE(bmpLabelGlyph8, wxImage(15, 23), wxT("LabelGlyph8"));
DEFINE_IMAGE(bmpLabelGlyph9, wxImage(15, 23), wxT("LabelGlyph9"));
DEFINE_IMAGE(bmpLabelGlyph10, wxImage(15, 23), wxT("LabelGlyph10"));
DEFINE_IMAGE(bmpLabelGlyph11, wxImage(15, 23), wxT("LabelGlyph11"));

SET_THEME_FLAGS(resFlagNewLine);
DEFINE_IMAGE(bmpSyncLockSelTile, wxImage(20, 22), wxT("SyncLockSelTile"));
DEFINE_IMAGE(bmpSyncLockTracksDown, wxImage(20, 20), wxT("SyncLockTracksDown"));
DEFINE_IMAGE(bmpSyncLockTracksUp, wxImage(20, 20), wxT("SyncLockTracksUp"));
DEFINE_IMAGE(bmpSyncLockTracksDisabled, wxImage(20, 20), wxT("SyncLockTracksDisabled"));
DEFINE_IMAGE(bmpSyncLockIcon, wxImage(12, 12), wxT("SyncLockIcon"));
DEFINE_IMAGE(bmpEditEffects, wxImage(21, 20), wxT("EditEffects"));
DEFINE_IMAGE(bmpToggleScrubRuler, wxImage(20, 20), wxT("ToggleScrubRuler"));
DEFINE_IMAGE(bmpHelpIcon, wxImage(21, 21), wxT("HelpIcon"));

SET_THEME_FLAGS(resFlagNone);
DEFINE_IMAGE(bmpPlayPointer, wxImage(20, 20), wxT("PlayPointer"));
DEFINE_IMAGE(bmpRecordPointer, wxImage(20, 20), wxT("RecordPointer"));
DEFINE_IMAGE(bmpGrabberDropLoc, wxImage(20, 20), wxT("GrabberDropLoc"));
DEFINE_IMAGE(bmpSliderThumb, wxImage(20, 20), wxT("SliderThumb"));
DEFINE_IMAGE(bmpSliderThumbHilited, wxImage(20, 20), wxT("SliderThumbHilited"));
DEFINE_IMAGE(bmpSliderThumbRotated, wxImage(20, 20), wxT("SliderThumbRotated"));
DEFINE_IMAGE(bmpSliderThumbRotatedHilited, wxImage(20, 20), wxT("SliderThumbRotatedHilited"));

SET_THEME_FLAGS(resFlagNewLine);
DEFINE_IMAGE(bmpUpButtonExpand, wxImage(96, 18), wxT("UpButtonExpand"));
DEFINE_IMAGE(bmpDownButtonExpand, wxImage(96, 18), wxT("DownButtonExpand"));
DEFINE_IMAGE(bmpHiliteUpButtonExpand, wxImage(96, 18), wxT("HiliteUpButtonExpand"));
DEFINE_IMAGE(bmpHiliteButtonExpand, wxImage(96, 18), wxT("HiliteButtonExpand"));
DEFINE_IMAGE(bmpUpButtonExpandSel, wxImage(96, 18), wxT("UpButtonExpandSel"));
DEFINE_IMAGE(bmpDownButtonExpandSel, wxImage(96, 18), wxT("DownButtonExpandSel"));
DEFINE_IMAGE(bmpHiliteUpButtonExpandSel, wxImage(96, 18), wxT("HiliteUpButtonExpandSel"));
DEFINE_IMAGE(bmpHiliteButtonExpandSel, wxImage(96, 18), wxT("HiliteButtonExpandSel"));

SET_THEME_FLAGS(resFlagNone);
DEFINE_IMAGE(bmpUpButtonLarge, wxImage(48, 48), wxT("UpButtonLarge"));
DEFINE_IMAGE(bmpDownButtonLarge, wxImage(48, 48), wxT("DownButtonLarge"));
DEFINE_IMAGE(bmpHiliteUpButtonLarge, wxImage(48, 48), wxT("HiliteUpButtonLarge"));
DEFINE_IMAGE(bmpHiliteButtonLarge, wxImage(48, 48), wxT("HiliteButtonLarge"));

SET_THEME_FLAGS(resFlagNewLine);

SET_THEME_FLAGS(resFlagNone);
DEFINE_IMAGE(bmpUpButtonSmall, wxImage(27, 27), wxT("UpButtonSmall"));
DEFINE_IMAGE(bmpDownButtonSmall, wxImage(27, 27), wxT("DownButtonSmall"));
DEFINE_IMAGE(bmpHiliteUpButtonSmall, wxImage(27, 27), wxT("HiliteUpButtonSmall"));
DEFINE_IMAGE(bmpHiliteButtonSmall, wxImage(27, 27), wxT("HiliteButtonSmall"));

SET_THEME_FLAGS(resFlagNewLine);

SET_THEME_FLAGS(resFlagInternal);
DEFINE_IMAGE(bmpRecoloredUpLarge, wxImage(36, 36), wxT("RecoloredUpLarge"));
DEFINE_IMAGE(bmpRecoloredDownLarge, wxImage(36, 36), wxT("RecoloredDownLarge"));
DEFINE_IMAGE(bmpRecoloredUpHiliteLarge, wxImage(36, 36), wxT("RecoloredUpHiliteLarge"));
DEFINE_IMAGE(bmpRecoloredHiliteLarge, wxImage(36, 36), wxT("RecoloredHiliteLarge"));
DEFINE_IMAGE(bmpRecoloredUpSmall, wxImage(27, 27), wxT("RecoloredUpSmall"));
DEFINE_IMAGE(bmpRecoloredDownSmall, wxImage(27, 27), wxT("RecoloredDownSmall"));
DEFINE_IMAGE(bmpRecoloredUpHiliteSmall, wxImage(27, 27), wxT("RecoloredUpHiliteSmall"));
DEFINE_IMAGE(bmpRecoloredHiliteSmall, wxImage(27, 27), wxT("RecoloredHiliteSmall"));

SET_THEME_FLAGS(resFlagCursor);
DEFINE_IMAGE(bmpIBeamCursor, wxImage(32, 32), wxT("IBeamCursor"));
DEFINE_IMAGE(bmpCrosshairCursor, wxImage(32, 32), wxT("CrosshairCursor"));
DEFINE_IMAGE(bmpDrawCursor, wxImage(32, 32), wxT("DrawCursor"));
DEFINE_IMAGE(bmpEnvCursor, wxImage(32, 32), wxT("EnvCursor"));
DEFINE_IMAGE(bmpTimeCursor, wxImage(32, 32), wxT("TimeCursor"));
DEFINE_IMAGE(bmpZoomInCursor, wxImage(32, 32), wxT("ZoomInCursor"));
DEFINE_IMAGE(bmpZoomOutCursor, wxImage(32, 32), wxT("ZoomOutCursor"));
DEFINE_IMAGE(bmpLabelCursorLeft, wxImage(32, 32), wxT("LabelCursorLeft"));
DEFINE_IMAGE(bmpLabelCursorRight, wxImage(32, 32), wxT("LabelCursorRight"));
DEFINE_IMAGE(bmpDisabledCursor, wxImage(32, 32), wxT("DisabledCursor"));
DEFINE_IMAGE(bmpBottomFrequencyCursor, wxImage(32, 32), wxT("BottomFrequencyCursor"));
DEFINE_IMAGE(bmpTopFrequencyCursor, wxImage(32, 32), wxT("TopFrequencyCursor"));
DEFINE_IMAGE(bmpBandWidthCursor, wxImage(32, 32), wxT("BandWidthCursor"));
DEFINE_IMAGE(bmpSubViewsCursor, wxImage(32, 32), wxT("SubViewsCursor"));

SET_THEME_FLAGS(resFlagNewLine);
DEFINE_IMAGE(bmpAudacityLogo48x48, wxImage(48, 48), wxT("AudacityLogo48x48"));
