#
# GNU makefile
#

topdir = ../../..
libdir = $(topdir)/objs/$(BUILD)/lib

ifeq ($(OS),Darwin)
    EXPLICIT_LIBS = $(libdir)/libFLAC.a $(libdir)/libreplaygain_analysis.a $(OGG_EXPLICIT_LIBS) -lm
else
    LIBS = -lFLAC -lreplaygain_analysis $(OGG_LIBS) -lm
endif

LIB_NAME = libgrabbag
INCLUDES = -I$(topdir)/include

SRCS_C = \
	alloc.c \
	cuesheet.c \
	file.c \
	picture.c \
	replaygain.c \
	seektable.c

include $(topdir)/build/lib.mk

# DO NOT DELETE THIS LINE -- make depend depends on it.
