#!/usr/bin/env python

# Minimal waf script for projects that include waflib directly

from waflib import Context, Scripting

import inspect
import os

def main():
    script_path = os.path.abspath(inspect.getfile(inspect.getmodule(main)))
    project_path = os.path.dirname(script_path)
    Scripting.waf_entry_point(os.getcwd(), Context.WAFVERSION, project_path)

if __name__ == '__main__':
    main()
