#!/bin/bash
# SoX Resampler Library       Copyright (c) 2007-13 robs@users.sourceforge.net
# Licence for this file: LGPL v2.1                  See LICENCE for details.

len=8
#vg="valgrind --leak-check=full --show-reachable=yes"

$vg ./1-single-block

ir=96000
or=44100
for i in 1 2; do
  prev=""
  sox -r $ir -n 0.f32 synth $len sin 0+`expr $ir / 2`
  for f in `find . -type f -executable -name "[2-4]*"`; do
    $vg $f $ir $or < 0.f32 > $f.f32
    test x$prev != x && cmp $f.f32 $prev
    prev=$f.f32
  done
  or=96000
  ir=44100
done
rm *.f32

rm ?.png
for n in 0 1 2 3; do
  $vg ./5-variable-rate $n | sox -tf32 -r44100 -c1 - -n spectrogram -hwk -o $n.png -X 50
  vg=""
done
