EXTRA_DIST += \
	libsoxr/add-make-check-support.patch \
	libsoxr/AUTHORS \
	libsoxr/CMakeLists.txt \
	libsoxr/cmake/Modules/FindLibAVCodec.cmake \
	libsoxr/cmake/Modules/FindOpenMP.cmake \
	libsoxr/cmake/Modules/FindSIMD.cmake \
	libsoxr/cmake/Modules/TestBigEndian.cmake \
	libsoxr/configure \
	libsoxr/COPYING.LGPL \
	libsoxr/deinstall.cmake.in \
	libsoxr/examples/1a-lsr.c \
	libsoxr/examples/1-single-block.c \
	libsoxr/examples/2-stream.C \
	libsoxr/examples/3-options-input-fn.c \
	libsoxr/examples/4-split-channels.c \
	libsoxr/examples/5-variable-rate.c \
	libsoxr/examples/CMakeLists.txt \
	libsoxr/examples/examples-common.h \
	libsoxr/examples/README \
	libsoxr/go \
	libsoxr/go.bat \
	libsoxr/INSTALL \
	libsoxr/inst-check \
	libsoxr/inst-check-soxr \
	libsoxr/LICENCE \
	libsoxr/msvc/libsoxr.vcproj \
	libsoxr/msvc/README \
	libsoxr/msvc/soxr-config.h \
	libsoxr/NEWS \
	libsoxr/README \
	libsoxr/soxr-config.h.in \
	libsoxr/src/aliases.h \
	libsoxr/src/avfft32.c \
	libsoxr/src/avfft32s.c \
	libsoxr/src/ccrw2.h \
	libsoxr/src/CMakeLists.txt \
	libsoxr/src/data-io.c \
	libsoxr/src/data-io.h \
	libsoxr/src/dbesi0.c \
	libsoxr/src/fft4g32.c \
	libsoxr/src/fft4g32s.c \
	libsoxr/src/fft4g64.c \
	libsoxr/src/fft4g.c \
	libsoxr/src/fft4g_cache.h \
	libsoxr/src/fft4g.h \
	libsoxr/src/fifo.h \
	libsoxr/src/filter.c \
	libsoxr/src/filter.h \
	libsoxr/src/filters.h \
	libsoxr/src/half_coefs.h \
	libsoxr/src/half-fir.h \
	libsoxr/src/internal.h \
	libsoxr/src/libsoxr-dev.src.in \
	libsoxr/src/libsoxr.src.in \
	libsoxr/src/lsr.c \
	libsoxr/src/pffft32.c \
	libsoxr/src/pffft32s.c \
	libsoxr/src/pffft.c \
	libsoxr/src/pffft.h \
	libsoxr/src/poly-fir0.h \
	libsoxr/src/poly-fir.h \
	libsoxr/src/rate32.c \
	libsoxr/src/rate32s.c \
	libsoxr/src/rate64.c \
	libsoxr/src/rate.h \
	libsoxr/src/rdft.h \
	libsoxr/src/rint-clip.h \
	libsoxr/src/rint.h \
	libsoxr/src/samplerate.h \
	libsoxr/src/simd.c \
	libsoxr/src/simd-dev.h \
	libsoxr/src/simd.h \
	libsoxr/src/soxr.c \
	libsoxr/src/soxr.h \
	libsoxr/src/soxr-lsr.h \
	libsoxr/src/soxr-lsr.pc.in \
	libsoxr/src/soxr.pc.in \
	libsoxr/src/vr32.c \
	libsoxr/tests/CMakeLists.txt \
	libsoxr/tests/cmp-test.cmake \
	libsoxr/tests/eg-test \
	libsoxr/tests/io-test \
	libsoxr/tests/large-ratio \
	libsoxr/tests/README \
	libsoxr/tests/vector-cmp.c \
	libsoxr/tests/vector-gen.c \
	libsoxr/TODO \
	$(NULL)
