lin_dbg:
  script:
    - python ./waf -dsT --no-coverage configure build test

lin_rel:
  script:
    - python ./waf -sT --no-coverage configure build test

mac_dbg:
  script:
    - python ./waf -dsT --no-coverage configure build test
  tags:
    - macos

mac_rel:
  script:
    - python ./waf -sT --no-coverage configure build test
  tags:
    - macos

win_dbg:
  script:
    - python ./waf -dsT --no-coverage configure build test
  tags:
    - windows

win_rel:
  script:
    - python ./waf -sT --no-coverage configure build test
  tags:
    - windows