.TH LV2APPLY 1 "05 Sep 2016"

.SH NAME
.B lv2apply \- apply an LV2 plugin to an audio file
.SH SYNOPSIS
.B lv2apply [OPTION]... PLUGIN_URI

.SH OPTIONS
.TP
\fB\-i IN_FILE\fR
Input file

.TP
\fB\-o OUT_FILE\fR
Output file

.TP
\fB\-c SYM VAL\fR
Set control port SYM to VAL

.TP
\fB\-\-help\fR
Display help and exit

.TP
\fB\-\-version\fR
Display version information and exit

.SH "SEE ALSO"
.BR lv2ls(1)
.BR lv2info(1)

.SH AUTHOR
lv2apply was written by David Robillard <d@drobilla.net>
