.TH LV2INFO 1 "05 Sep 2016"

.SH NAME
.B lv2info \- print information about an installed LV2 plugin
.SH SYNOPSIS
.B lv2info PLUGIN_URI

.SH OPTIONS
.TP
\fB\-p FILE\fR
Write Turtle description of plugin to FILE

.TP
\fB\-m FILE\fR
Add record of plugin to manifest FILE

.TP
\fB\-\-help\fR
Display help and exit

.TP
\fB\-\-version\fR
Display version information and exit

.SH "SEE ALSO"
.BR lilv(3),
.BR lv2ls(1)

.SH AUTHOR
lv2info was written by David Robillard <d@drobilla.net>
.PP
This manual page was written by Jaromír Mikes <mira.mikes@seznam.cz>
and David Robillard <d@drobilla.net>
