#!/bin/sh
#
# You can use this to build wxWidgets.  Just run it from within the root of the
# wxWidgets source tree like so:
#
#  sudo <path to this script>/build_wxwidgets
#



# Build a specific configuration
function bld
{
   rm -rf "${1}"
   mkdir -p "${1}"
   pushd "${1}"
   shift

   ../configure --disable-accessibility \
                --enable-macosx-arch=i386 \
                --with-expat=builtin \
                --with-zlib=builtin \
                --with-regex=builtin \
                --enable-universal_binary=no \
                --enable-unicode=yes \
                --enable-webkit=no \
                --with-macosx-version-min=10.10 \
                ${@}
   export LDFLAGS="${LDFLAGS1}"
   xcrun make -j 4
   export LDFLAGS=""
   popd
}

# Install a specific configuration
function inst
{
   pushd "${1}"
   xcrun make install
   popd
}

# Build all configurations
bld bld_debug --enable-debug=yes --enable-shared=yes --with-flavour=debug
bld bld_release --enable-debug=no --enable-shared=yes --with-flavour=release

# Install all configurations
inst bld_debug
inst bld_release
