name: '[AU4] Update: Learn playlists'

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode: stable, testing'
        required: true
        default: 'testing'

defaults:
  run:
    shell: bash

jobs:
  au4_update_playlists:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Update info about the get started playlist in s3
        run: |
          S3_URL="s3://extensions.musescore.org/audacity/4.0/learn/started_playlist.json"
          if [ ${{ github.event.inputs.mode }} == "testing" ]; then
            S3_URL="s3://extensions.musescore.org/audacity/4.0/learn/started_playlist.test.json"
          fi

          sudo bash ./buildscripts/ci/learn/make_playlists_info_file.sh \
            --youtube_api_key ${{ secrets.YOUTUBE_API_KEY }} \
            --youtube_playlist_id 'PLt__f9D3T90yZiTOE1QOAF2Uc1MPAK_fv'

          sudo bash ./buildscripts/ci/tools/s3_push_file.sh \
            --s3_key ${{ secrets.S3_KEY }} \
            --s3_secret ${{ secrets.S3_SECRET }} \
            --s3_url ${S3_URL} \
            --file_path "playlist.json"
